### ISSUE TITLE
RuntimeError: index out of range at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:193

### ISSUE THREAD

**Issue by 199688** [rucnyz/MMGCN#1]
您好，我严格对其了代码环境，并且按照readme运行后出现如下问题，请问这个如何解决

Data has been loaded.
Now, training start ...
  0%|                                                  | 0/1929 [00:00<?, ?it/s]/home/wb415/mtt/MM/MMGCN-master/Model_MMGCN.py:64: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  temp_features = torch.tensor(temp_features,dtype=torch.float32)
Traceback (most recent call last):
  File "/home/wb415/mtt/MM/MMGCN-master/main.py", line 91, in <module>
    loss = train(epoch, len(train_dataset), train_dataloader, model, optimizer, batch_size, writer)
  File "/home/wb415/mtt/MM/MMGCN-master/Train.py", line 17, in train
    loss, model_loss, reg_loss, weight_loss, entropy_loss = model.loss(user_tensor, item_tensor)
  File "/home/wb415/mtt/MM/MMGCN-master/Model_MMGCN.py", line 143, in loss
    out = self.forward()
  File "/home/wb415/mtt/MM/MMGCN-master/Model_MMGCN.py", line 133, in forward
    t_rep = self.t_gcn(self.t_feat, self.id_embedding)
  File "/home/wb415/miniconda3/envs/mtt3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wb415/mtt/MM/MMGCN-master/Model_MMGCN.py", line 68, in forward
    h = F.leaky_relu(self.conv_embed_1(x, self.edge_index))  # equation 1
  File "/home/wb415/miniconda3/envs/mtt3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wb415/mtt/MM/MMGCN-master/BaseModel.py", line 23, in forward
    return self.propagate(edge_index, size = (x.size(0), x.size(0)), x = x)
  File "/home/wb415/miniconda3/envs/mtt3.6/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 101, in propagate
    tmp = torch.index_select(tmp, 0, edge_index[idx])
RuntimeError: index out of range at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:193
  0%|                                                  | 0/1929 [00:00<?, ?it/s]

**Comment by rucnyz** [comment]
您好，针对您说的问题我已做修改，将Model_MMGCN.py文件中的full_accuracy函数参数step改成100即可运行，原step2000是针对大数据集使用的，我在这里使用的是toy dataset，故报错。但我暂时没有研究代码中的GCN逻辑，运行结果不一定合理。
另外我并非本文作者，使用该代码为学习使用，欢迎和您继续交流
